### ISSUE TITLE
allegro5 make problem

### ISSUE THREAD

**Issue by betterpig** [leoll2/Autoparking#6]
hello leoll2, I just install the allegro5 as you instructed, but when I run the make command ,there are some problems. before the make all dependencies have been install and update as shown in terminal.the problem log is below.by the way,my system is ubuntu 18.04 and python 3.7.5.

/Autoparking/allegro5/src/opengl/extensions.c:799:25: error: ‘ALLEGRO_OGL_EXT_API {aka struct ALLEGRO_OGL_EXT_API}’ has no member named ‘GetString’
    glGetString = ext_api->GetString;

**Comment by leoll2** [comment]
What Allegro version are you trying to install? Did you checkout 5.2.4?
It's been a while since I last installed Autoparking, if you're still experiencing the issue then I can try a fresh installation on a Ubuntu 18.04 machine and verify that everything still works.  Let me know!
